# TO Create: conda env create --file conda_env.yml
# To Update: conda env update --file conda_env.yml
# To Export: conda env export --file conda_env.yml
name: HT-CapsNet
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - graphviz=2.38
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - ipykernel
  - python=3.9
  - pip
  - pip:
      - absl-py==1.0.0
      - anyio==3.6.2
      - appdirs==1.4.4
      - array-record==0.4.0
      - astor==0.8.1
      - astunparse==1.6.3
      - babel==2.11.0
      - beautifulsoup4==4.11.1
      - bigtree==0.10.3
      - bokeh==3.1.1
      - cachetools==5.0.0
      - charset-normalizer==2.0.12
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - contourpy==1.1.1
      - cycler==0.11.0
      - daiquiri==3.0.1
      - dask==2023.5.0
      - datashader==0.15.2
      - datashape==0.5.2
      - dill==0.3.4
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - emnist==0.0
      - et-xmlfile==1.1.0
      - etils==1.3.0
      - fastjsonschema==2.16.2
      - filelock==3.13.1
      - flatbuffers==2.0
      - fonttools==4.29.1
      - fsspec==2024.2.0
      - future==0.18.2
      - gast==0.5.3
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==2.6.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.55.0
      - grpcio==1.43.0
      - gviz-api==1.10.0
      - h5py==3.6.0
      - hiclass==4.4.0
      - holoviews==1.17.1
      - huggingface-hub==0.21.3
      - idna==3.3
      - imageio==2.16.1
      - importlib-metadata==5.0.0
      - importlib-resources==5.4.0
      - ipynbname==2023.1.0.0
      - ipyparams==0.2.1
      - jinja2==3.1.2
      - joblib==1.1.0
      - json5==0.9.10
      - jupyter-contrib-core==0.3.3
      - jupyter-contrib-nbextensions==0.5.1
      - jupyter-core==5.0.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-latex-envs==1.4.6
      - jupyter-nbextensions-configurator==0.4.1
      - jupyter-server==1.23.1
      - jupyterlab==3.5.0
      - jupyterlab-server==2.16.2
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.3.2
      - kornia==0.7.1
      - libclang==13.0.0
      - linkify-it-py==2.0.3
      - llvmlite==0.38.0
      - locket==1.0.0
      - lxml==4.8.0
      - markdown==3.3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.5.1
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mistune==2.0.4
      - multipledispatch==1.0.0
      - nbclassic==0.4.8
      - nbconvert==7.2.4
      - nbformat==5.7.0
      - networkx==2.7.1
      - notebook-shim==0.2.2
      - numpy==1.21.5
      - nvidia-ml-py==11.525.84
      - nvitop==1.0.0
      - oauthlib==3.2.0
      - opencv-python==4.5.5.64
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - pandas==1.4.1
      - panel==1.2.3
      - param==2.1.0
      - partd==1.4.1
      - pillow==9.0.1
      - pip==24.2
      - platformdirs==2.5.3
      - plotly==5.24.0
      - prettytable==3.3.0
      - promise==2.3
      - protobuf==3.20.3
      - psutil==5.9.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyct==0.5.0
      - pydot==1.4.2
      - python-json-logger==2.0.2
      - pytz==2021.3
      - pyviz-comms==3.0.2
      - pywavelets==1.3.0
      - pyyaml==6.0
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - rsa==4.8
      - safetensors==0.4.2
      - scikit-image==0.19.2
      - scikit-learn==1.0.2
      - scipy==1.8.0
      - seaborn==0.11.2
      - sentry-sdk==1.40.6
      - setproctitle==1.3.3
      - sklearn-hierarchical-classification==1.3.2
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - tabulate==0.8.10
      - tenacity==9.0.0
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-profile==2.5.0
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.8.1
      - tensorflow-datasets==4.9.2
      - tensorflow-docs
      - tensorflow-estimator==2.8.0
      - tensorflow-gpu==2.8.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.24.0
      - tensorflow-metadata==1.7.0
      - termcolor==1.1.0
      - texttable==1.6.7
      - tf-estimator-nightly==2.8.0.dev2021122109
      - tf-keras==2.15.0
      - tf-slim==1.1.0
      - threadpoolctl==3.1.0
      - tifffile==2022.3.16
      - timm==0.9.16
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==1.13.0
      - torchvision==0.14.0
      - tqdm==4.63.0
      - treelib==1.6.1
      - typing-extensions==4.1.1
      - uc-micro-py==1.0.3
      - umap==0.1.1
      - umap-learn==0.5.6
      - upsetplot==0.9.0
      - upsetty==0.1.3
      - urllib3==1.26.18
      - voila==0.4.0
      - wandb==0.16.3
      - websocket-client==1.4.2
      - websockets==10.4
      - werkzeug==2.0.3
      - wget==3.2
      - windows-curses==2.3.1
      - wrapt==1.13.3
      - xarray==2023.1.0
      - xyzservices==2024.4.0
